//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using LibraryManagement.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIDG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIDG()
        {
            this.THEDOCGIAs = new HashSet<THEDOCGIA>();
        }
    
        public int MaLDG { get; set; }

        private string _TenDG;
        public string TenLDG { get => _TenDG; set { _TenDG = value; OnPropertyChanged(); } }

        public int Xoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEDOCGIA> THEDOCGIAs { get; set; }
    }
}
