//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Model
{
    using LibraryManagement.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN:BaseViewModel
    {
        public int MaNV { get; set; }

        private string _TenNV;
        public string TenNV { get => _TenNV; set { _TenNV = value; OnPropertyChanged(); } }

        private System.DateTime _NgaySinh;
        public System.DateTime NgaySinh { get => _NgaySinh; set { _NgaySinh = value; OnPropertyChanged(); } }

        private string _DiaChi;
        public string DiaChi { get => _DiaChi; set { _DiaChi = value; OnPropertyChanged(); } }

        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }

        private string _TenDangNhap;
        public string TenDangNhap { get => _TenDangNhap; set { _TenDangNhap = value; OnPropertyChanged(); } }
        
        public string MatKhau { get; set; }
        public int MaLNV { get; set; }
        public int Xoa { get; set; }

        private LOAINV _lOAINV;
        public virtual LOAINV LOAINV { get => _lOAINV; set { _lOAINV = value; OnPropertyChanged(); } }
    }
}
